MVC/Models/brokers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class brokers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public brokers()
        {
            this.appointments = new HashSet<appointments>();
        }
    
        public int idBroker { get; set; }
		[DisplayName("Nom du courtier")]
		public string lastname { get; set; }
		[DisplayName("Prenom du courtier")]
		public string firstname { get; set; }
		[DisplayName("Mail")]
		public string mail { get; set; }
		[DisplayName("Télephone")]
		public string phoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointments> appointments { get; set; }
    }
}

MVC/Controllers/appointementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using System.Text.RegularExpressions; //pour utilisation des regex

namespace MVC.Controllers
{
    public class appointementsController : Controller
    {
        private agendaEntities2 db = new agendaEntities2();

		// GET: Home
		public ActionResult listAppointements()
		{
			var appointments = db.appointments.Include(a => a.brokers).Include(a => a.customers).OrderBy(x => x.dateHour);
			return View(appointments.ToList());
        }

        // GET: Home/Create
        public ActionResult addAppointements(int? id)
        {
			if(id == null)
			{
				ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "lastname");
				ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "lastname");
				return View();
			}
			else
			{
				ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "lastname", id);
				ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "lastname");
				return View();
			}
        }

        // POST: Home/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier.
        // Pour plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addAppointements([Bind(Include = "idAppointment,dateHour,idBroker,idCustomer")] appointments appointmentToAdd)
        {
			var date = Request.Form["startDatepicker"];//Récupération de la date du rdv dans la variable du même nom sous forme de string 
			var hour = Request.Form["startTimepicker"];//Récupération de l'heure du rdv dans la variable Hour sous forme de string
			var concat = date + " " + hour;//concaténation des 2 variables de sorte à correspondre au format DateTime
			appointmentToAdd.dateHour = Convert.ToDateTime(concat);//attribution de la valeur convertie au format datetime à l'attribut dateHour de l'objet appointmentToAdd
			var brokerAlreadyUsed = db.appointments.Where(x => x.idBroker == appointmentToAdd.idBroker && x.dateHour == appointmentToAdd.dateHour).SingleOrDefault();
			if (brokerAlreadyUsed != null)
			{
				ModelState.AddModelError("dateHour", "Ce courtier possède déjà un rendez-vous à cette date");
			}
			var customerAlreadyUsed = db.appointments.Where(x => x.idCustomer == appointmentToAdd.idCustomer && x.dateHour == appointmentToAdd.dateHour).SingleOrDefault();
			if (customerAlreadyUsed != null)
			{
				ModelState.AddModelError("dateHour", "Ce client possède déjà un rendez-vous à cette date");
			}
			if (ModelState.IsValid)
            {
                db.appointments.Add(appointmentToAdd);
                db.SaveChanges();
                return RedirectToAction("listAppointements");
            }

            ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "lastname", appointmentToAdd.idBroker);
            ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "lastname", appointmentToAdd.idCustomer);
            return View(appointmentToAdd);
        }

        // GET: Home/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
				return View("Error");
            }
            appointments appointments = db.appointments.Find(id);
            if (appointments == null)
            {
				return View("PageNotFound");
            }
            ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "lastname", appointments.idBroker);
            ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "lastname", appointments.idCustomer);
			return View(appointments);
        }

        // POST: Home/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idAppointment,dateHour,idBroker,idCustomer")] appointments appointments)
        {
			ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "lastname", appointments.idBroker);
			ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "lastname", appointments.idCustomer);
			if (ModelState.IsValid)
            {
                db.Entry(appointments).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("listAppointements");
            }
            return View(appointments);
        }

        // GET: Home/Delete/5
        public ActionResult Delete(int? id)
        {
            appointments appointments = db.appointments.Find(id);
            if (appointments == null)
            {
                return View("PageNotFound");
            }
            return View(appointments);
        }

        // POST: Home/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            appointments appointments = db.appointments.Find(id);
            db.appointments.Remove(appointments);
            db.SaveChanges();
            return RedirectToAction("listAppointements");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC/Controllers/brokersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using System.Text.RegularExpressions; //pour utilisation des regex

namespace MVC.Controllers
{
    public class brokersController : Controller
    {
		string regexName = @"^[A-Za-zéèàêâôûùïüç\-]+$";
		string regexMail = @"[0-9a-zA-Z\.\-]+@[0-9a-zA-Z\.\-]+.[a-zA-Z]{2,4}";
		string regexPhone = @"^[0][0-9]{9}";

		private agendaEntities2 db = new agendaEntities2();

		// GET: brokers
		//SQLQuery permet d'utiliser une Requete SQL dans le Controleur
		public ActionResult listBrokers()
        {
            return View(db.brokers.ToList());
        }

		//Vue de l'ôpération réussi
		public ActionResult Succes()
		{
			return View("Succes");
		}

		// GET: brokers/Create
		public ActionResult addBrokers()
        {
            return View();
        }

        // POST: brokers/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addBrokers([Bind(Include = "idBroker,lastname,firstname,mail,phoneNumber")] brokers brokerToAdd)
        {
			//Vérification que le champ lastname n'est pas null ou vide
			if (!String.IsNullOrEmpty(brokerToAdd.lastname)) //si le champ lastname n'est pas vide ou null on vérifie la validité de l'entrée
			{
				//Vérification de la validité de l'entrée
				if (!Regex.IsMatch(brokerToAdd.lastname, regexName)) //si l'entrée utilisateur ne passe pas la regex ajout d'un message d'erreur
				{
					//Message d'erreur
					ModelState.AddModelError("lastname", "Ecrire un nom valide");
				}
			}
			else
			{
				//Message d'erreur si le champ lastname est vide ou null
				ModelState.AddModelError("lastname", "Ecrire un nom");
			}
			//Vérification que le champ firstname n'est pas null ou vide
			if (!String.IsNullOrEmpty(brokerToAdd.firstname))
			{
				//Vérification de la validité de l'entrée
				if (!Regex.IsMatch(brokerToAdd.firstname, regexName))
				{
					//Message d'erreur
					ModelState.AddModelError("firstname", "Ecrire un prénom valide");
				}
			}
			else
			{
				//Message d'erreur
				ModelState.AddModelError("firstname", "Ecrire un prénom");
			}
			//Vérification que le champ mail n'est pas null ou vide
			if (!String.IsNullOrEmpty(brokerToAdd.mail))
			{
				//Creation de la variable isAlreadyUsed qui permet de verifier qu'un mail n'est pas attribuer a deux client different
				var isAlreadyUsed = db.brokers.Where(bro => bro.mail == brokerToAdd.mail).SingleOrDefault();
				//Vérification de la validité de l'entrée
				if (!Regex.IsMatch(brokerToAdd.mail, regexMail))
				{
					//Message d'erreur
					ModelState.AddModelError("mail", "Ecrire un mail valide");
				}
				else if (isAlreadyUsed != null)
				{
					ModelState.AddModelError("Mail", "un courtier a déjà la même adresse mail");
				}
			}
			else
			{
				//Message d'erreur
				ModelState.AddModelError("mail", "Ecrire un mail");
			}
			//Vérification que le champ phoneNumber n'est pas null ou vide
			if (!String.IsNullOrEmpty(brokerToAdd.phoneNumber))
			{
				//Vérification de la validité de l'entrée
				if (!Regex.IsMatch(brokerToAdd.phoneNumber, regexPhone))
				{
					//Message d'erreur
					ModelState.AddModelError("phoneNumber", "Ecrire un téléphone valide");
				}
			}
			else
			{
				//Message d'erreur
				ModelState.AddModelError("phoneNumber", "Ecrire un téléphone");
			}

			//si il n'y a pas d'erreur
			if (ModelState.IsValid)
            {
                db.brokers.Add(brokerToAdd);
                db.SaveChanges();
                return RedirectToAction("Succes");
            }
			else
			{
				return View(brokerToAdd);
			}
        }

		// GET: brokers/Edit/5
		public ActionResult Edit(int? id)
        {
            brokers brokers = db.brokers.Find(id);
            if (brokers == null)
            {
				return View("PageNotFound");
			}
            return View(brokers);
        }

        // POST: brokers/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idBroker,lastname,firstname,mail,phoneNumber")] brokers brokers)
        {
			//Vérification que le champ lastname n'est pas null ou vide
			if (!String.IsNullOrEmpty(brokers.lastname)) //si le champ lastname n'est pas vide ou null on vérifie la validité de l'entrée
			{
				//Vérification de la validité de l'entrée
				if (!Regex.IsMatch(brokers.lastname, regexName)) //si l'entrée utilisateur ne passe pas la regex ajout d'un message d'erreur
				{
					//Message d'erreur
					ModelState.AddModelError("lastname", "Ecrire un nom valide");
				}
			}
			else
			{
				//Message d'erreur si le champ lastname est vide ou null
				ModelState.AddModelError("lastname", "Ecrire un nom");
			}
			//Vérification que le champ firstname n'est pas null ou vide
			if (!String.IsNullOrEmpty(brokers.firstname))
			{
				//Vérification de la validité de l'entrée
				if (!Regex.IsMatch(brokers.firstname, regexName))
				{
					//Message d'erreur
					ModelState.AddModelError("firstname", "Ecrire un prénom valide");
				}
			}
			else
			{
				//Message d'erreur
				ModelState.AddModelError("firstname", "Ecrire un prénom");
			}
			//Vérification que le champ mail n'est pas null ou vide
			if (!String.IsNullOrEmpty(brokers.mail))
			{
				//Vérification de la validité de l'entrée
				if (!Regex.IsMatch(brokers.mail, regexMail))
				{
					//Message d'erreur
					ModelState.AddModelError("mail", "Ecrire un mail valide");
				}
			}
			else
			{
				//Message d'erreur
				ModelState.AddModelError("mail", "Ecrire un mail");
			}
			//Vérification que le champ phoneNumber n'est pas null ou vide
			if (!String.IsNullOrEmpty(brokers.phoneNumber))
			{
				//Vérification de la validité de l'entrée
				if (!Regex.IsMatch(brokers.phoneNumber, regexPhone))
				{
					//Message d'erreur
					ModelState.AddModelError("phoneNumber", "Ecrire un téléphone valide");
				}
			}
			else
			{
				//Message d'erreur
				ModelState.AddModelError("phoneNumber", "Ecrire un téléphone");
			}

			if (ModelState.IsValid)
            {
                db.Entry(brokers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Succes");
            }
			else
			{
				return View(brokers);
			}
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC/Views/brokers/Edit.cshtml
@model MVC.Models.brokers

@{
    ViewBag.Title = "Edit";
}

<h2>Editer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Courtiers</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idBroker)

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "listBrokers")
</div>

MVC/Views/brokers/PageNotFound.cshtml
@{
	ViewBag.Title = "PageNotFound";
}

<img src="https://assets-ouch.icons8.com/preview/295/50d4ecc4-d9a4-43a1-bd8e-2fe55c8dc1ef.png" />

MVC/Views/brokers/Succes.cshtml
@{
    ViewBag.Title = "Succes";
}

<div class="text-center text-success">
	<h2>Votre WWWWWAAAAAAAAAAAAHHHHHHWHAAAAAAGGGGGGGGG est un succes</h2>
	@Html.ActionLink("Retour à la liste", "listBrokers")
</div>

MVC/Views/brokers/addBrokers.cshtml
@model MVC.Models.brokers

@{
    ViewBag.Title = "addBrokers";
}

<h2>Ajouter une Courtier</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Courtiers</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.lastname, "Nom", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "listBrokers")
</div>

MVC/Views/brokers/listBrokers.cshtml
@model IEnumerable<MVC.Models.brokers>
<!--permet l'affichage des données correspondants au model choisi-->
@{
	ViewBag.Title = "listBrokers";
}

<h2>Courtiers</h2>

<p>
	@Html.ActionLink("Ajouter un nouveau Courtier", "addBrokers")
</p>
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.lastname)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.firstname)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.mail)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.phoneNumber)
		</th>
	</tr>
	<!--affichage du tableau-->
	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.lastname)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.firstname)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.mail)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.phoneNumber)
			</td>
			<td>
				@Html.ActionLink("Editer", "Edit", new { id = item.idBroker }) |
				@Html.ActionLink("Ajouter un RDV", "addBrokers", "appointements", new { id = item.idBroker}, null)
			</td>
		</tr>
	}
</table>